name: ai_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.5.2
  device_info_plus: ^10.1.2
  crypto: ^3.0.3
  uuid: ^4.5.1
  timeago: ^3.6.1
  http: ^1.2.0
  http_parser: ^4.0.2
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  fl_chart: ^0.66.2
  
  
  # 音频处理相关库
  opus_flutter: ^3.0.3
  opus_dart: ^3.0.1
  flutter_sound: ^9.26.0
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  flutter_pcm_player: ^0.0.1
  record: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_displaymode: ^0.6.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^4.0.0
  flutter_blue_plus: ^1.35.3
  audio_streamer: ^4.1.1
  vad: ^0.0.8  # Silero VAD 语音活动检测，用于自动唤醒
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "robot_3.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "robot_3.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "robot_3.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "robot_3.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "robot_3.png"

flutter:
  uses-material-design: true
